engines:
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Design/CouplingBetweenObjects:
        enabled: false