engines:
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Design/CouplingBetweenObjects:
        enabled: false
      Naming/LongVariable:
        enabled: false
      Naming/ShortMethodName:
        enabled: false
      UnusedFormalParameter:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false