engines:
  duplication:
    enabled: true
    config:
      languages:
        php:

  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
      Design/CouplingBetweenObjects:
        enabled: false
      Naming/LongVariable:
        enabled: false
      Naming/ShortMethodName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      UnusedFormalParameter:
        enabled: false

ratings:
  paths:
    - "**.js"
    - "**.php"

exclude_paths:
  - tests/
  - docs/
  - common/messages/
  - common/migrations/
  - common/runtime/