language: php

php:
  - 5.5
  - 5.6
  - 7.0
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - |
    if [ $TRAVIS_PHP_VERSION != '5.6' ]; then
        phpenv config-rm xdebug.ini
    fi
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2" "codeception/codeception:^2.0" "codeception/specify" "codeception/verify"
  - travis_retry composer install --prefer-dist --no-interaction

# setup application:
  - |
    cp .env.dist .env
    sed -i s/yii2-starter-kit\.dev/localhost:8080/ .env

before_script:
  - mysql -e 'CREATE DATABASE `yii2-starter-kit-test`;';
  - php tests/codeception/bin/yii app/setup --interactive=0

script:
  - |
    php -S localhost:8080 > /dev/null 2>&1 &
    cd tests
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      ./../vendor/bin/codecept run --debug --coverage --coverage-xml
    else
      ./../vendor/bin/codecept run --debug
    fi

after_success:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      cd ..
      travis_retry ./vendor/bin/coveralls -v
    fi

notifications:
  email: false