<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2017-10-15 21:52:02
 */
return [
    'vendor' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot',
        'baseUrl' => '@web',
        'js' => [
            'bundle/vendor.js',
        ],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => '@bower/jquery/dist',
        'js' => [],
        'css' => [],
        'depends' => [
            'vendor',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => '@yii/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'vendor',
        ],
    ],
];