<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2018-12-04 22:19:50
 */
return [
    'vendor' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot',
        'baseUrl' => '@web',
        'js' => [
            'bundle/vendor.js',
        ],
        'css' => [
            'bundle/vendor.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => '@bower/jquery/dist',
        'js' => [],
        'css' => [],
        'depends' => [
            'vendor',
        ],
    ],
    'yii\\jui\\JuiAsset' => [
        'sourcePath' => '@bower/jquery-ui',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'vendor',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => '@bower/bootstrap/dist',
        'js' => [],
        'css' => [],
        'depends' => [
            'vendor',
        ],
    ],
    'yii\\bootstrap\\BootstrapPluginAsset' => [
        'sourcePath' => '@bower/bootstrap/dist',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'vendor',
        ],
    ],
    'common\\assets\\FontAwesome' => [
        'sourcePath' => '@bower/font-awesome',
        'js' => [],
        'css' => [],
        'depends' => [
            'vendor',
        ],
    ],
    'common\\assets\\JquerySlimScroll' => [
        'sourcePath' => '@bower/jquery-slimscroll',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'vendor',
        ],
    ],
    'common\\assets\\AdminLte' => [
        'sourcePath' => '@bower/admin-lte/dist',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\jui\\JuiAsset',
            'yii\\bootstrap\\BootstrapPluginAsset',
            'common\\assets\\FontAwesome',
            'common\\assets\\JquerySlimScroll',
            'vendor',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => '@yii/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'vendor',
        ],
    ],
    'common\\assets\\JqueryMigrateAsset' => [
        'sourcePath' => '@bower/jquery-migrate',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'vendor',
        ],
    ],
    'yii\\validators\\ValidationAsset' => [
        'sourcePath' => '@yii/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'vendor',
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'sourcePath' => '@yii/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'vendor',
        ],
    ],
    'yii\\grid\\GridViewAsset' => [
        'sourcePath' => '@yii/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'vendor',
        ],
    ],
    'yii\\widgets\\PjaxAsset' => [
        'sourcePath' => '@bower/yii2-pjax',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'vendor',
        ],
    ],
    'kartik\\form\\ActiveFormAsset' => [
        'sourcePath' => '@base/vendor/kartik-v/yii2-widget-activeform/src/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\widgets\\ActiveFormAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'yii\\bootstrap\\BootstrapPluginAsset',
            'vendor',
        ],
    ],
    '\\kartik\\dialog\\DialogAsset' => [
        'sourcePath' => '@base/vendor/kartik-v/yii2-dialog/src/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\bootstrap\\BootstrapAsset',
            'vendor',
        ],
    ],
    'kartik\\grid\\GridViewAsset' => [
        'sourcePath' => '@base/vendor/kartik-v/yii2-grid/src/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            '\\kartik\\dialog\\DialogAsset',
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'vendor',
        ],
    ],
    'kartik\\dialog\\DialogAsset' => [
        'sourcePath' => '@base/vendor/kartik-v/yii2-dialog/src/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\bootstrap\\BootstrapAsset',
            'vendor',
        ],
    ],
    'kartik\\dialog\\DialogBootstrapAsset' => [
        'sourcePath' => '@base/vendor/kartik-v/yii2-dialog/src/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'kartik\\dialog\\DialogAsset',
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'yii\\bootstrap\\BootstrapPluginAsset',
            'vendor',
        ],
    ],
    'kartik\\grid\\GridExportAsset' => [
        'sourcePath' => '@base/vendor/kartik-v/yii2-grid/src/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'kartik\\dialog\\DialogAsset',
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'vendor',
        ],
    ],
    'kartik\\grid\\GridResizeColumnsAsset' => [
        'sourcePath' => '@base/vendor/kartik-v/yii2-grid/src/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'kartik\\grid\\GridViewAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'vendor',
        ],
    ],
    'kartik\\base\\WidgetAsset' => [
        'sourcePath' => '@base/vendor/kartik-v/yii2-krajee-base/src/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'vendor',
        ],
    ],
    'kartik\\select2\\Select2Asset' => [
        'sourcePath' => '@base/vendor/kartik-v/yii2-widget-select2/src/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'vendor',
        ],
    ],
    'kartik\\select2\\ThemeKrajeeAsset' => [
        'sourcePath' => '@base/vendor/kartik-v/yii2-widget-select2/src/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'kartik\\select2\\Select2Asset',
            'yii\\bootstrap\\BootstrapAsset',
            'vendor',
        ],
    ],
    'shirase\\grid\\sortable\\SortableAsset' => [
        'sourcePath' => '@base/vendor/shirase55/yii2-sortable/assets',
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\jui\\JuiAsset',
            'vendor',
        ],
    ],
];