<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'API access token' => '',
    'Canonical' => '',
    'Canonical ID' => '',
    'Expire At' => '',
    'Gallery' => 'Галерея',
    'Images' => 'Изображения',
    'Link' => '',
    'No' => '',
    'Not Active' => 'Не активирован',
    'Blocked' => 'Заблокирован',
    'Page' => 'Страница',
    'Page description' => '',
    'Page keywords' => '',
    'Page title' => '',
    'Parent ID' => '',
    'Plugin' => '',
    'Redirect ID' => '',
    'Route' => '',
    'Template' => 'Шаблон',
    'Token' => '',
    'Uri' => '',
    'Widget' => '',
    'Widget Param' => '',
    'Yes' => '',
    'Показывать' => '',
    'Тип' => '',
    '"{attribute}" must be a valid JSON' => '"{attribute}" должен содержать валидный JSON',
    'Active' => 'Активен',
    'Article ID' => 'ID Статьи',
    'Attachments' => 'Вложения',
    'Author' => 'Автор',
    'Base Url' => 'Базовый Url',
    'Body' => 'Текст',
    'Categories' => 'Разделы',
    'Comment' => 'Комментарий',
    'Component' => 'Компонент',
    'Created At' => 'Создано',
    'Created at' => 'Создано',
    'Deleted' => 'Удалено',
    'Down to maintenance.' => 'Закрыто на обслуживание',
    'E-mail' => 'E-mail',
    'Firstname' => 'Имя',
    'Gender' => 'Пол',
    'ID' => 'ID',
    'Image' => 'Изображение',
    'Key' => 'Ключ',
    'Last login' => 'Последний вход',
    'Lastname' => 'Фамилия',
    'Locale' => 'Локаль',
    'Middlename' => 'Отчество',
    'Name' => 'Название',
    'Order' => 'Порядок',
    'Path' => 'Путь',
    'Picture' => 'Аватар',
    'Published' => 'Опубликовано',
    'Published At' => 'Дата публикации',
    'Size' => 'Размер',
    'Slug' => 'ЧПУ',
    'Status' => 'Статус',
    'Thumbnail' => 'Эскиз изображения',
    'Title' => 'Заголовок',
    'Type' => 'Тип',
    'Updated At' => 'Обновлено',
    'Updated at' => 'Последнее обновление',
    'Updater' => 'Обновивщий',
    'Upload Ip' => 'IP',
    'Url' => 'Url',
    'User ID' => 'ID пользователя',
    'Username' => 'Имя пользователя',
    'Value' => 'Значение',
];
